### ISSUE TITLE
Feature request: Multiple file support

### ISSUE THREAD

**Issue by treborxy** [lrademacher/PDFTag#18]
Hi, thank you for your tool, pretty helpful! 
--- EDIT: Sorry, didn't notice there is the 'multiselect' branch ----
Even more helpful it would be, if one could edit tags for multiple files at once. 
What do you think, was that lots of work to do?

**Comment by treborxy** [comment]
My bad, see above

**Comment by lrademacher** [comment]
Yeah, also duplicates #5. Maybe in the coming winter i will find time for the improvement
